PATH=%PATH%;C:\bin
PATH=%PATH%;C:\ProgramData\Oracle\Java\javapath
PATH=%PATH%;C:\Program Files (x86)\nodejs\
PATH=%PATH%;C:\ProgramData\chocolatey\bin
PATH=%PATH%;C:\Program Files\Microsoft\Web Platform Installer\
PATH=%PATH%;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\
PATH=%PATH%;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\
PATH=%PATH%;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
PATH=%PATH%;C:\Program Files\doxygen\bin
PATH=%PATH%;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
PATH=%PATH%;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\
PATH=%PATH%;C:\Users\Bruce\AppData\Roaming\npm
